name: Build and push docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/marge-server:latest .

      - name: push
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/marge-server:latest
